version: '2'
services:
    bdddemo-app:
        image: bdddemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bdddemo-mysql:3306/bdddemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bdddemo-mysql:
        extends:
            file: mysql.yml
            service: bdddemo-mysql
